imports:
    - resource: parameters.yml

framework:
    #todo: change to a random string
    secret: TeMpOrArYsEcReT
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    templating:
        engines: ['php']
    default_locale:  en
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true