outlandishgmh:
    resource: "@OutlandishSiteBundle/Controller"
    prefix: /
    type: annotation
	

defaultPost:
    path: /{slugs}/
    requirements:
        slugs: "[\w-\/]+"
    defaults:
        _controller: SiteBundle:Default:defaultPost