site_controllers:
    resource: "@OutlandishSiteBundle/Controller"
    prefix: /
    type: annotation

default_post:
    path: /{slugs}/
    requirements:
        slugs: "[\w-\/]+"
    defaults:
        _controller: SiteBundle:Default:defaultPost